using System;

namespace XPub.Resources
{
    public static class StaticStings
    {
        public static string Section3 = @"PROVIDING FOR CONSIDERATION OF H.R. 842 PROTECTING THE 
RIGHT TO ORGANIZE ACT OF 2021; PROVIDING FOR 
CONSIDERATION OF H. R. 8. BIPARTISAN BACKGROUND CHECKS
ACR OF 2010;  PROVIDING FOR CONSIDERATION OF H. R. 1446
ENHANCED BACKGROUND CHECKS ACTS OF 2021; AND FOR 
OTHER PURPOSES";

        public static string Section1 = @"IN RECOGNITION OF THE NATIONA; TRANSPORTATION SAFETY
BOARDS WORK TO IMPLEMENT POSITIVE TRAIN CONTROL";

        public static string Section2 = @"IN HONOR OF ED ""Butch"" AND THE CORRESPONDING 
BRIGADE 2 WE ACKHOWLEGE THERE HEORICS! ";
    }
}
