//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPub.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XPubResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XPubResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPub.Resources.XPubResource", typeof(XPubResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminConfigure.
        /// </summary>
        public static string AdminConfigMenuItenDisplay {
            get {
                return ResourceManager.GetString("AdminConfigMenuItenDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminConfigCreateJob.
        /// </summary>
        public static string AdminConfigNavigationPath {
            get {
                return ResourceManager.GetString("AdminConfigNavigationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Human Resources.
        /// </summary>
        public static string AdminHRMenuItenDisplay {
            get {
                return ResourceManager.GetString("AdminHRMenuItenDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminEmployees.
        /// </summary>
        public static string AdminHRNavigationPath {
            get {
                return ResourceManager.GetString("AdminHRNavigationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string DisplayMemberPath {
            get {
                return ResourceManager.GetString("DisplayMemberPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Assigned Work.
        /// </summary>
        public static string EmployeeAssignedWorkMenuItemDisplay {
            get {
                return ResourceManager.GetString("EmployeeAssignedWorkMenuItemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAssignedWork.
        /// </summary>
        public static string EmployeeAssignedWorkNavigationPath {
            get {
                return ResourceManager.GetString("EmployeeAssignedWorkNavigationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropAddress.
        /// </summary>
        public static string PropAddress {
            get {
                return ResourceManager.GetString("PropAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignedTasks.
        /// </summary>
        public static string PropAssignedTasks {
            get {
                return ResourceManager.GetString("PropAssignedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string PropBirthDate {
            get {
                return ResourceManager.GetString("PropBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateJobPopUp.
        /// </summary>
        public static string PropCreateJobPopUp {
            get {
                return ResourceManager.GetString("PropCreateJobPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateJobTitle.
        /// </summary>
        public static string PropCreateJobTitle {
            get {
                return ResourceManager.GetString("PropCreateJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRecordJobs.
        /// </summary>
        public static string PropCreateRecordJobs {
            get {
                return ResourceManager.GetString("PropCreateRecordJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string PropDepartment {
            get {
                return ResourceManager.GetString("PropDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayMemberPath.
        /// </summary>
        public static string PropDisplayMemberPath {
            get {
                return ResourceManager.GetString("PropDisplayMemberPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PropEmail {
            get {
                return ResourceManager.GetString("PropEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeInformation.
        /// </summary>
        public static string PropEmployeeInformation {
            get {
                return ResourceManager.GetString("PropEmployeeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluations.
        /// </summary>
        public static string PropEvaluations {
            get {
                return ResourceManager.GetString("PropEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string PropFirstName {
            get {
                return ResourceManager.GetString("PropFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string PropHeader {
            get {
                return ResourceManager.GetString("PropHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HireDate.
        /// </summary>
        public static string PropHireDate {
            get {
                return ResourceManager.GetString("PropHireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePhone.
        /// </summary>
        public static string PropHomePhone {
            get {
                return ResourceManager.GetString("PropHomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageUri.
        /// </summary>
        public static string PropImageUri {
            get {
                return ResourceManager.GetString("PropImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsBusy.
        /// </summary>
        public static string PropIsBusy {
            get {
                return ResourceManager.GetString("PropIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string PropLastName {
            get {
                return ResourceManager.GetString("PropLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListBoxCollection.
        /// </summary>
        public static string PropListBoxCollection {
            get {
                return ResourceManager.GetString("PropListBoxCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string PropMessage {
            get {
                return ResourceManager.GetString("PropMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePhone.
        /// </summary>
        public static string PropMobilePhone {
            get {
                return ResourceManager.GetString("PropMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationPath.
        /// </summary>
        public static string PropNavigationPath {
            get {
                return ResourceManager.GetString("PropNavigationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalProfile.
        /// </summary>
        public static string PropPersonalProfile {
            get {
                return ResourceManager.GetString("PropPersonalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string PropPhoto {
            get {
                return ResourceManager.GetString("PropPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string PropPrefix {
            get {
                return ResourceManager.GetString("PropPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProbationReason.
        /// </summary>
        public static string PropProbationReason {
            get {
                return ResourceManager.GetString("PropProbationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordModels.
        /// </summary>
        public static string PropRecordModels {
            get {
                return ResourceManager.GetString("PropRecordModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string PropSkype {
            get {
                return ResourceManager.GetString("PropSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PropStatus {
            get {
                return ResourceManager.GetString("PropStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskPools.
        /// </summary>
        public static string PropTaskPools {
            get {
                return ResourceManager.GetString("PropTaskPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PropTitle {
            get {
                return ResourceManager.GetString("PropTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitIndicatorContent.
        /// </summary>
        public static string PropWaitIndicatorContent {
            get {
                return ResourceManager.GetString("PropWaitIndicatorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Configure.
        /// </summary>
        public static string SupervisorConfigMenuItemDisplay {
            get {
                return ResourceManager.GetString("SupervisorConfigMenuItemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupervisorConfigCreateJob.
        /// </summary>
        public static string SupervisorConfigNavigationPath {
            get {
                return ResourceManager.GetString("SupervisorConfigNavigationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Job Management.
        /// </summary>
        public static string SupervisorJobManagementMenuItenDisplay {
            get {
                return ResourceManager.GetString("SupervisorJobManagementMenuItenDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupervisorJobManagement.
        /// </summary>
        public static string SupervisorJobManagementNavigationPath {
            get {
                return ResourceManager.GetString("SupervisorJobManagementNavigationPath", resourceCulture);
            }
        }
    }
}
